<h1 align="center"> DATA PROCESSING - DATA ENCODING</h1>

In [1]:
import pandas as pd
# preprocessing is a submodule and LabelEncoder 
from sklearn.preprocessing import LabelEncoder

In [20]:
df = pd.read_excel(r"C:\Users\ELCOT\Desktop\JananiMurugan\Machine_Learning\Dataset\ML_data.xlsx")
df

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,101,CSE,85,78.0,12,0,Female,Pass
1,102,IT,62,45.0,5,2,Male,Fail
2,103,CSE,91,88.0,15,0,Female,Pass
3,104,ECE,74,NaN,8,1,Male,Pass
4,105,IT,55,39.0,4,3,Female,Fail

In [3]:
# sample() selects random rows from the DataFrame.
df.sample(2)

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
3,104,ECE,74,NaN,8,1,Male,Pass
1,102,IT,62,45.0,5,2,Male,Fail

In [4]:
# head() selects the first rows of the DataFrame.
df.head(3)

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,101,CSE,85,78.0,12,0,Female,Pass
1,102,IT,62,45.0,5,2,Male,Fail
2,103,CSE,91,88.0,15,0,Female,Pass

## FEATURES

In [5]:
# 0-> means rows and 1 -> means columns
# here i  want to remove the empty value so  remove that column
X=df.drop("Final_Result",axis=1)
X

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender
0,101,CSE,85,78.0,12,0,Female
1,102,IT,62,45.0,5,2,Male
2,103,CSE,91,88.0,15,0,Female
3,104,ECE,74,NaN,8,1,Male
4,105,IT,55,39.0,4,3,Female

### TARGET

In [6]:
y=df["Final_Result"]
y

0    Pass
1    Fail
2    Pass
3    Pass
4    Fail
Name: Final_Result, dtype: str

In [7]:
# to find whether it has a null values in df 
df.isnull()

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False

In [8]:
# to count how many null values(true_values) there
df.isnull().sum()

Student_ID        0
Department        0
Attendance        0
Internal_Marks    1
Study_Hours       0
Backlogs          0
Gender            0
Final_Result      0
dtype: int64

# Imputation
### (Imputation means filling the missing values)
## Mean Imputation

In [9]:
# to replace the null values with value 
# I want to replace the values using mean..so i took internal marks column . 
df["Internal_Marks"]=df["Internal_Marks"].fillna(df['Internal_Marks'].mean())
df["Internal_Marks"]

0    78.0
1    45.0
2    88.0
3    62.5
4    39.0
Name: Internal_Marks, dtype: float64

## Median Imputation

In [10]:
# I want to replace the values using mean..so i took internal marks column . 
df["Internal_Marks"]=df["Internal_Marks"].fillna(df['Internal_Marks'].median())
df["Internal_Marks"]

0    78.0
1    45.0
2    88.0
3    62.5
4    39.0
Name: Internal_Marks, dtype: float64

## LABEL_ENCODING
## (Is better in binary categorical column)
### Use in Ordinal_category

In [11]:
#  to creat an object of LabelEncoder class
encoder=LabelEncoder()

In [12]:
# Ordered → Label/Ordinal Encoding
df["Gender_encoded"]=encoder.fit_transform(df["Gender"])

In [13]:
# To assign 0 -> for female and 1-> for men...in ascending order /  (Female , men)
df[["Gender","Gender_encoded"]]

   Gender  Gender_encoded
0  Female               0
1    Male               1
2  Female               0
3    Male               1
4  Female               0

In [14]:
df["Department_encoded"]=encoder.fit_transform(df["Department"])

In [15]:
# to  sort them using ascending / alphabetic order
df[["Department","Department_encoded"]]

  Department  Department_encoded
0        CSE                   0
1         IT                   2
2        CSE                   0
3        ECE                   1
4         IT                   2

## ONE_HOT ENCODING 
### Used for Nominal_category in pandas

In [16]:
# Unordered → One-Hot Encoding
pd.get_dummies(df,columns=["Department"])

,Student_ID,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result,Gender_encoded,Department_encoded,Department_CSE,Department_ECE,Department_IT
0,101,85,78.0,12,0,Female,Pass,0,0,True,False,False
1,102,62,45.0,5,2,Male,Fail,1,2,False,False,True
2,103,91,88.0,15,0,Female,Pass,0,0,True,False,False
3,104,74,62.5,8,1,Male,Pass,1,1,False,True,False
4,105,55,39.0,4,3,Female,Fail,0,2,False,False,True