In [ ]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import  LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [92]:
# for linear regression
%pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in C:\Users\ELCOT\AppData\Roaming\Python\Python314\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\ELCOT\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\ELCOT\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\ELCOT\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\ELCOT\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\ELCOT\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\ELCOT\AppData\Roaming\Python\Python314\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

In [4]:
df=pd.read_excel(r"C:\Users\ELCOT\Desktop\JananiMurugan\Machine_Learning\Dataset\Practice_data.xlsx")
df

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
0,1001,CSE,Male,82.0,7.5,68.0,9.0,78
1,1002,IT,Female,91.0,8.2,74.0,10.0,86
2,1003,ECE,Male,76.0,5.5,61.0,7.0,70
3,1004,AI&DS,Female,88.0,7.0,79.0,9.0,84
4,1005,BBA,Female,72.0,4.0,58.0,6.0,64
5,1006,CSE,Male,95.0,9.0,88.0,10.0,94
6,1007,IT,Female,67.0,3.5,52.0,5.0,59
7,1008,ECE,Male,84.0,6.5,70.0,8.0,77
8,1009,AI&DS,Female,79.0,6.0,66.0,8.0,73
9,1010,CSE,Female,93.0,8.5,82.0,10.0,90
10,1011,BBA,Male,69.0,4.5,55.0,6.0,62
11,1012,IT,Male,87.0,7.8,76.0,9.0,83
12,1013,ECE,Female,74.0,5.0,63.0,7.0,69
13,1014,AI&DS,Male,90.0,8.0,85.0,9.0,88
14,1015,CSE,Female,81.0,NaN,72.0,8.0,79
15,1016,IT,Male,78.0,5.8,NaN,7.0,72
16,1017,ECE,Female,NaN,6.2,67.0,8.0,75
17,1018,AI&DS,Male,86.0,7.2,73.0,NaN,82
18,1019,BBA,Female,65.0,3.0,49.0,5.0,55
19,1020,CSE,Male,89.0,7.5,81.0,9.0,86
20,1021,IT,Female,83.0,6.8,71.0,8.0,80
21,1022,ECE,Male,71.0,4.8,59.0,6.0,66
22,1023,AI&DS,Female,94.0,9.2,89.0,10.0,96
23,1024,CSE,Male,77.0,5.2,64.0,7.0,71
24,1025,BBA,Female,73.0,4.2,57.0,6.0,63
25,1006,CSE,Male,95.0,9.0,88.0,10.0,94
26,1012,IT,Male,87.0,7.8,76.0,9.0,83
27,1020,CSE,Male,89.0,7.5,81.0,9.0,86

In [ ]:
# To check the data types
df.dtypes

Student_ID                 int64
Department                   str
Gender                       str
Attendance_Pct           float64
Study_Hours_Per_Day      float64
Internal_Marks           float64
Assignments_Completed    float64
Final_Score                int64
dtype: object

In [10]:
df.head(5)

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
0,1001,CSE,Male,82.0,7.5,68.0,9.0,78
1,1002,IT,Female,91.0,8.2,74.0,10.0,86
2,1003,ECE,Male,76.0,5.5,61.0,7.0,70
3,1004,AI&DS,Female,88.0,7.0,79.0,9.0,84
4,1005,BBA,Female,72.0,4.0,58.0,6.0,64

In [13]:
df.tail(3)

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
25,1006,CSE,Male,95.0,9.0,88.0,10.0,94
26,1012,IT,Male,87.0,7.8,76.0,9.0,83
27,1020,CSE,Male,89.0,7.5,81.0,9.0,86

In [ ]:
# The following code tells how many  rows and columns in the  data set
df.shape

(28, 8)

In [80]:
# To find missing values
df.isnull()

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score,Gender_encoded,Department_enocoded,Department_encoded
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False

In [8]:
# To sum of the null values
df.isnull().sum()

Student_ID               0
Department               0
Gender                   0
Attendance_Pct           1
Study_Hours_Per_Day      1
Internal_Marks           1
Assignments_Completed    1
Final_Score              0
dtype: int64

In [45]:
# Imputing the  values into  that null values
df["Attendance_Pct"]=df["Attendance_Pct"].fillna(df["Attendance_Pct"].median()).round()
df["Attendance_Pct"]

0     82.0
1     91.0
2     76.0
3     88.0
4     72.0
5     95.0
6     67.0
7     84.0
8     79.0
9     93.0
10    69.0
11    87.0
12    74.0
13    90.0
14    81.0
15    78.0
16    82.0
17    86.0
18    65.0
19    89.0
20    83.0
21    71.0
22    94.0
23    77.0
24    73.0
25    95.0
26    87.0
27    89.0
Name: Attendance_Pct, dtype: float64

In [46]:
# Imputing the values into  study_hours column to replce the null values
df["Study_Hours_Per_Day"]=df["Study_Hours_Per_Day"].fillna(df["Study_Hours_Per_Day"].median())
df["Study_Hours_Per_Day"]

0     7.5
1     8.2
2     5.5
3     7.0
4     4.0
5     9.0
6     3.5
7     6.5
8     6.0
9     8.5
10    4.5
11    7.8
12    5.0
13    8.0
14    6.5
15    5.8
16    6.2
17    7.2
18    3.0
19    7.5
20    6.8
21    4.8
22    9.2
23    5.2
24    4.2
25    9.0
26    7.8
27    7.5
Name: Study_Hours_Per_Day, dtype: float64

In [47]:
# Imputing the values into  internal_marks column to replce the null values
df["Internal_Marks"]=df["Internal_Marks"].fillna(df["Internal_Marks"].median()).round(1)
df["Internal_Marks"]

0     68.0
1     74.0
2     61.0
3     79.0
4     58.0
5     88.0
6     52.0
7     70.0
8     66.0
9     82.0
10    55.0
11    76.0
12    63.0
13    85.0
14    72.0
15    70.5
16    67.0
17    73.0
18    49.0
19    81.0
20    71.0
21    59.0
22    89.0
23    64.0
24    57.0
25    88.0
26    76.0
27    81.0
Name: Internal_Marks, dtype: float64

In [48]:
# Imputing the values into Assignments_Completed column to replce the null values
df["Assignments_Completed"]=df["Assignments_Completed"].fillna(df["Assignments_Completed"].median()).round()
df["Assignments_Completed"]

0      9.0
1     10.0
2      7.0
3      9.0
4      6.0
5     10.0
6      5.0
7      8.0
8      8.0
9     10.0
10     6.0
11     9.0
12     7.0
13     9.0
14     8.0
15     7.0
16     8.0
17     8.0
18     5.0
19     9.0
20     8.0
21     6.0
22    10.0
23     7.0
24     6.0
25    10.0
26     9.0
27     9.0
Name: Assignments_Completed, dtype: float64

In [49]:
# again to  check whether our dataset has null values or not
df.isnull().sum()

Student_ID               0
Department               0
Gender                   0
Attendance_Pct           0
Study_Hours_Per_Day      0
Internal_Marks           0
Assignments_Completed    0
Final_Score              0
dtype: int64

In [ ]:
# To check  where duplicates available in dataset
print(df.duplicated().sum())
print(df[df.duplicated(keep=False)])

3
    Student_ID Department Gender  Attendance_Pct  Study_Hours_Per_Day  \
5         1006        CSE   Male            95.0                  9.0
11        1012         IT   Male            87.0                  7.8
19        1020        CSE   Male            89.0                  7.5
25        1006        CSE   Male            95.0                  9.0
26        1012         IT   Male            87.0                  7.8
27        1020        CSE   Male            89.0                  7.5

    Internal_Marks  Assignments_Completed  Final_Score
5             88.0                   10.0           94
11            76.0                    9.0           83
19            81.0                    9.0           86
25            88.0                   10.0           94
26            76.0                    9.0           83
27            81.0                    9.0           86

In [53]:
# Remove the duplicates
df=df.drop_duplicates()

# To check againn for finding duplicates
print(df.duplicated().sum())

0

In [78]:
df

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score,Gender_encoded,Department_enocoded,Department_encoded
0,1001,2,Male,0.112422,0.711395,-0.109101,0.787839,78,1,2,2
1,1002,4,Female,1.166382,1.124997,0.445652,1.444371,86,0,4,4
2,1003,3,Male,-0.590217,-0.470324,-0.756314,-0.525226,70,1,3,3
3,1004,0,Female,0.815062,0.415965,0.907946,0.787839,84,0,0,0
4,1005,1,Female,-1.058644,-1.356614,-1.033690,-1.181758,64,0,1,1
5,1006,2,Male,1.634808,1.597685,1.740076,1.444371,94,1,2,2
6,1007,4,Female,-1.644177,-1.652044,-1.588444,-1.838290,59,0,4,4
7,1008,3,Male,0.346636,0.120535,0.075816,0.131306,77,1,3,3
8,1009,0,Female,-0.238897,-0.174894,-0.294019,0.131306,73,0,0,0
9,1010,2,Female,1.400595,1.302255,1.185323,1.444371,90,0,2,2
10,1011,1,Male,-1.409964,-1.061184,-1.311067,-1.181758,62,1,1,1
11,1012,4,Male,0.697955,0.888653,0.630570,0.787839,83,1,4,4
12,1013,3,Female,-0.824431,-0.765754,-0.571396,-0.525226,69,0,3,3
13,1014,0,Male,1.049275,1.006825,1.462700,0.787839,88,1,0,0
14,1015,2,Female,-0.004684,0.120535,0.260734,0.131306,79,0,2,2
15,1016,4,Male,-0.356004,-0.293066,0.122046,-0.525226,72,1,4,4
16,1017,3,Female,0.112422,-0.056723,-0.201560,0.131306,75,0,3,3
17,1018,0,Male,0.580849,0.534137,0.353193,0.131306,82,1,0,0
18,1019,1,Female,-1.878390,-1.947474,-1.865820,-1.838290,55,0,1,1
19,1020,2,Male,0.932169,0.711395,1.092864,0.787839,86,1,2,2
20,1021,4,Female,0.229529,0.297793,0.168275,0.131306,80,0,4,4
21,1022,3,Male,-1.175750,-0.883926,-0.941231,-1.181758,66,1,3,3
22,1023,0,Female,1.517702,1.715857,1.832535,1.444371,96,0,0,0
23,1024,2,Male,-0.473111,-0.647582,-0.478937,-0.525226,71,1,2,2
24,1025,1,Female,-0.941537,-1.238442,-1.126149,-1.181758,63,0,1,1

In [79]:
# Features
X=df.drop("Final_Score",axis=1)
X

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Gender_encoded,Department_enocoded,Department_encoded
0,1001,2,Male,0.112422,0.711395,-0.109101,0.787839,1,2,2
1,1002,4,Female,1.166382,1.124997,0.445652,1.444371,0,4,4
2,1003,3,Male,-0.590217,-0.470324,-0.756314,-0.525226,1,3,3
3,1004,0,Female,0.815062,0.415965,0.907946,0.787839,0,0,0
4,1005,1,Female,-1.058644,-1.356614,-1.033690,-1.181758,0,1,1
5,1006,2,Male,1.634808,1.597685,1.740076,1.444371,1,2,2
6,1007,4,Female,-1.644177,-1.652044,-1.588444,-1.838290,0,4,4
7,1008,3,Male,0.346636,0.120535,0.075816,0.131306,1,3,3
8,1009,0,Female,-0.238897,-0.174894,-0.294019,0.131306,0,0,0
9,1010,2,Female,1.400595,1.302255,1.185323,1.444371,0,2,2
10,1011,1,Male,-1.409964,-1.061184,-1.311067,-1.181758,1,1,1
11,1012,4,Male,0.697955,0.888653,0.630570,0.787839,1,4,4
12,1013,3,Female,-0.824431,-0.765754,-0.571396,-0.525226,0,3,3
13,1014,0,Male,1.049275,1.006825,1.462700,0.787839,1,0,0
14,1015,2,Female,-0.004684,0.120535,0.260734,0.131306,0,2,2
15,1016,4,Male,-0.356004,-0.293066,0.122046,-0.525226,1,4,4
16,1017,3,Female,0.112422,-0.056723,-0.201560,0.131306,0,3,3
17,1018,0,Male,0.580849,0.534137,0.353193,0.131306,1,0,0
18,1019,1,Female,-1.878390,-1.947474,-1.865820,-1.838290,0,1,1
19,1020,2,Male,0.932169,0.711395,1.092864,0.787839,1,2,2
20,1021,4,Female,0.229529,0.297793,0.168275,0.131306,0,4,4
21,1022,3,Male,-1.175750,-0.883926,-0.941231,-1.181758,1,3,3
22,1023,0,Female,1.517702,1.715857,1.832535,1.444371,0,0,0
23,1024,2,Male,-0.473111,-0.647582,-0.478937,-0.525226,1,2,2
24,1025,1,Female,-0.941537,-1.238442,-1.126149,-1.181758,0,1,1

In [81]:
# Target
y=df["Final_Score"]
y

0     78
1     86
2     70
3     84
4     64
5     94
6     59
7     77
8     73
9     90
10    62
11    83
12    69
13    88
14    79
15    72
16    75
17    82
18    55
19    86
20    80
21    66
22    96
23    71
24    63
Name: Final_Score, dtype: int64

### LABEL_ENCODING for GENDER column
##### Because it is binary catagorical  column

In [97]:
#  to creat an object of LabelEncoder class
encoder=LabelEncoder()

##### ENCODE

In [98]:
df["Gender_encoded"]=encoder.fit_transform(df["Gender"])

In [99]:
# To assign 0 for female and 1 for male
df[["Gender","Gender_encoded"]]

    Gender  Gender_encoded
0     Male               1
1   Female               0
2     Male               1
3   Female               0
4   Female               0
5     Male               1
6   Female               0
7     Male               1
8   Female               0
9   Female               0
10    Male               1
11    Male               1
12  Female               0
13    Male               1
14  Female               0
15    Male               1
16  Female               0
17    Male               1
18  Female               0
19    Male               1
20  Female               0
21    Male               1
22  Female               0
23    Male               1
24  Female               0

In [69]:
# Encode Departments
encoder=LabelEncoder()
df["Department_encoded"]=encoder.fit_transform(df["Department"])
df[["Department","Department_encoded"]]

    Department  Department_encoded
0            2                   2
1            4                   4
2            3                   3
3            0                   0
4            1                   1
5            2                   2
6            4                   4
7            3                   3
8            0                   0
9            2                   2
10           1                   1
11           4                   4
12           3                   3
13           0                   0
14           2                   2
15           4                   4
16           3                   3
17           0                   0
18           1                   1
19           2                   2
20           4                   4
21           3                   3
22           0                   0
23           2                   2
24           1                   1

### ONE-HOT ENCODING for DEPARTMENT column
##### Because it is nominal

In [70]:
pd.get_dummies(df,columns=["Department"])

,Student_ID,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score,Gender_encoded,Department_enocoded,Department_encoded,Department_0,Department_1,Department_2,Department_3,Department_4
0,1001,Male,82.0,7.5,68.0,9.0,78,1,2,2,False,False,True,False,False
1,1002,Female,91.0,8.2,74.0,10.0,86,0,4,4,False,False,False,False,True
2,1003,Male,76.0,5.5,61.0,7.0,70,1,3,3,False,False,False,True,False
3,1004,Female,88.0,7.0,79.0,9.0,84,0,0,0,True,False,False,False,False
4,1005,Female,72.0,4.0,58.0,6.0,64,0,1,1,False,True,False,False,False
5,1006,Male,95.0,9.0,88.0,10.0,94,1,2,2,False,False,True,False,False
6,1007,Female,67.0,3.5,52.0,5.0,59,0,4,4,False,False,False,False,True
7,1008,Male,84.0,6.5,70.0,8.0,77,1,3,3,False,False,False,True,False
8,1009,Female,79.0,6.0,66.0,8.0,73,0,0,0,True,False,False,False,False
9,1010,Female,93.0,8.5,82.0,10.0,90,0,2,2,False,False,True,False,False
10,1011,Male,69.0,4.5,55.0,6.0,62,1,1,1,False,True,False,False,False
11,1012,Male,87.0,7.8,76.0,9.0,83,1,4,4,False,False,False,False,True
12,1013,Female,74.0,5.0,63.0,7.0,69,0,3,3,False,False,False,True,False
13,1014,Male,90.0,8.0,85.0,9.0,88,1,0,0,True,False,False,False,False
14,1015,Female,81.0,6.5,72.0,8.0,79,0,2,2,False,False,True,False,False
15,1016,Male,78.0,5.8,70.5,7.0,72,1,4,4,False,False,False,False,True
16,1017,Female,82.0,6.2,67.0,8.0,75,0,3,3,False,False,False,True,False
17,1018,Male,86.0,7.2,73.0,8.0,82,1,0,0,True,False,False,False,False
18,1019,Female,65.0,3.0,49.0,5.0,55,0,1,1,False,True,False,False,False
19,1020,Male,89.0,7.5,81.0,9.0,86,1,2,2,False,False,True,False,False
20,1021,Female,83.0,6.8,71.0,8.0,80,0,4,4,False,False,False,False,True
21,1022,Male,71.0,4.8,59.0,6.0,66,1,3,3,False,False,False,True,False
22,1023,Female,94.0,9.2,89.0,10.0,96,0,0,0,True,False,False,False,False
23,1024,Male,77.0,5.2,64.0,7.0,71,1,2,2,False,False,True,False,False
24,1025,Female,73.0,4.2,57.0,6.0,63,0,1,1,False,True,False,False,False

In [100]:
# Create X and y
X = df.drop(["Final_Score", "Gender", "Department"], axis=1)
y = df["Final_Score"]

##### Split the data into training and testing sets.

In [101]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [ ]:
print(X_train.shape)
print(X_test.shape)

# 20 rows → training data
# 5 rows → testing data
# 10 columns → features after your encoding

(20, 10)
(5, 10)

### SCALING
##### Using Standard_Scaler

In [102]:
num_cols = [
    "Attendance_Pct",
    "Study_Hours_Per_Day",
    "Internal_Marks",
    "Assignments_Completed"
]

std_scaler = StandardScaler()

X_train[num_cols] = std_scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = std_scaler.transform(X_test[num_cols])

In [103]:
# To print both train and test set
print("X_train:")
print(X_train[num_cols].head())

print("\nX_test:")
print(X_test[num_cols].head())

X_train:
    Attendance_Pct  Study_Hours_Per_Day  Internal_Marks  Assignments_Completed
9         1.282732             1.241907        1.056455               1.397151
13        0.963379             0.967755        1.308492               0.789694
1         1.069830             1.077416        0.384356               1.397151
22        1.389183             1.625720        1.644541               1.397151
5         1.495633             1.516059        1.560528               1.397151

X_test:
    Attendance_Pct  Study_Hours_Per_Day  Internal_Marks  Assignments_Completed
8        -0.207579            -0.128851       -0.287742               0.182237
16        0.111773            -0.019191       -0.203730               0.182237
0         0.111773             0.693604       -0.119718               0.789694
23       -0.420481            -0.567494       -0.455767              -0.425220
11        0.644027             0.858095        0.552381               0.789694

## LINEAR REGRESSION MODEL

In [ ]:
model=LinearRegression()

# Trains the model using:

# X_train → input/features (attendance, study hours, marks, etc.)
# y_train → actual Final_Score


# .fit() = teach the model using training data

model.fit(X_train, y_train)

LinearRegression()

In [ ]:
# The trained model takes the test features (X_test) and predicts the Final_Score.

y_pred = model.predict(X_test)

print(y_pred)

[74.24662786 75.58480476 79.69323862 69.02214577 84.10660861]

In [ ]:
# To cross compare the values
print("Actual:", y_test.values)
print("Predicted:", y_pred)

Actual: [73 75 78 71 83]
Predicted: [74.24662786 75.58480476 79.69323862 69.02214577 84.10660861]