<h1 align="center">PANDAS</h1>

In [ ]:
# IMPORTANT NOTE :- here all array values must be in same length

In [ ]:
# the followings are used to  inspect the data at initially

In [8]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\ELCOT\AppData\Roaming\Python\Python314\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\ELCOT\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ELCOT\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ELCOT\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\ELCOT\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Arun", "Priya", "Karthik", "Meena", "Rahul"],
    "Department": ["CSE", "IT", "CSE", "ECE", "IT"],
    "Attendance": [82, 91, 76, 68, 88],
    "Python": [85, 92, 76, 65, 88],
    "SQL": [78, 88, 82, 70, 91],
    "Excel": [90, 95, 80, 72, 86]
}

df=pd.DataFrame(data) # Dataframe
print(df)


# the following shows in  series manner
# print(data)

   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80
3         104    Meena        ECE          68      65   70     72
4         105    Rahul         IT          88      88   91     86

In [ ]:
# EDA = Exploratory Data Analysis

# It means examining and understanding a dataset before doing further analysis or modeling.

# In Python/Pandas, EDA commonly includes:

# df.head() → view data
# df.shape → rows & columns
# df.info() → data types & missing values
# df.describe() → statistical summary
# Checking missing values, duplicates, and patterns

# 👉 Shortly: EDA = understanding your data.

In [ ]:
# for rows these methods  are used..like head, tail, sample,..

# the following shows data in table manner so that data frame used

df=pd.DataFrame(data)

# Displays the entire DataFrame.
print(df)

# Displays only the first 5 rows by default.
print(df.head())

# It displays the first 3 rows of your DataFrame.
print(df.head(3))

# It displays the last 5 rows of the DataFrame by default.
print(df.tail())

# It displays the last 3 rows of the DataFrame.
print(df.tail(3))

   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80
3         104    Meena        ECE          68      65   70     72
4         105    Rahul         IT          88      88   91     86
   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80
3         104    Meena        ECE          68      65   70     72
4         105    Rahul         IT          88      88   91     86
   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80
   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80
3         104    Meena        ECE          68      65   70     72
4         105    Rahul         IT          88      88   91     86
   Student_ID     Name Department  Attendance  Python  SQL  Excel
2         103  Karthik        CSE          76      76   82     80
3         104    Meena        ECE          68      65   70     72
4         105    Rahul         IT          88      88   91     86

In [18]:
# it tooks the rows randomly
df.sample()

# it shows random 4 rows 
df.sample(4)

   Student_ID   Name Department  Attendance  Python  SQL  Excel
4         105  Rahul         IT          88      88   91     86
1         102  Priya         IT          91      92   88     95
3         104  Meena        ECE          68      65   70     72
0         101   Arun        CSE          82      85   78     90

In [23]:
# the following code tells the number of rows and columns in a DataFrame.
df.shape

(5, 7)

In [27]:
#  to find column names
df.columns

Index(['Student_ID', 'Name', 'Department', 'Attendance', 'Python', 'SQL',
       'Excel'],
      dtype='str')

In [ ]:
# the following code gives summary information about the DataFrame.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  5 non-null      int64
 1   Name        5 non-null      str
 2   Department  5 non-null      str
 3   Attendance  5 non-null      int64
 4   Python      5 non-null      int64
 5   SQL         5 non-null      int64
 6   Excel       5 non-null      int64
dtypes: int64(5), str(2)
memory usage: 412.0 bytes

In [ ]:
# it means getting a statistical summary of the numerical data in a DataFrame.
df.describe()

       Student_ID  Attendance     Python        SQL      Excel
count    5.000000    5.000000   5.000000   5.000000   5.000000
mean   103.000000   81.000000  81.200000  81.800000  84.600000
std      1.581139    9.273618  10.802777   8.318654   8.933085
min    101.000000   68.000000  65.000000  70.000000  72.000000
25%    102.000000   76.000000  76.000000  78.000000  80.000000
50%    103.000000   82.000000  85.000000  82.000000  86.000000
75%    104.000000   88.000000  88.000000  88.000000  90.000000
max    105.000000   91.000000  92.000000  91.000000  95.000000

In [36]:
# means select/access the Python column from the DataFrame df
# here vectorization concept used (because to check entire column's data type)
df["Python"]

0    85
1    92
2    76
3    65
4    88
Name: Python, dtype: int64

In [35]:
# means checking the data type of the Python column.
df["Python"].dtype

dtype('int64')

In [40]:
# to get multiple columns
df[["Name","Department","Python"]]

      Name Department  Python
0     Arun        CSE      85
1    Priya         IT      92
2  Karthik        CSE      76
3    Meena        ECE      65
4    Rahul         IT      88

### Indexing using lables and iloc

In [ ]:
# means select the first row of the DataFrame.
# iloc = select data using its integer position (index).
print(df.iloc[0])

Student_ID     101
Name          Arun
Department     CSE
Attendance      82
Python          85
SQL             78
Excel           90
Name: 0, dtype: object

In [ ]:
# to find the 4th row
print(df.iloc[3])

Student_ID      104
Name          Meena
Department      ECE
Attendance       68
Python           65
SQL              70
Excel            72
Name: 3, dtype: object

In [ ]:
#  multiple rows → 1st and 5th rows
print(df.iloc[[0,4]])

   Student_ID   Name Department  Attendance  Python  SQL  Excel
0         101   Arun        CSE          82      85   78     90
4         105  Rahul         IT          88      88   91     86

In [ ]:
# means select specific rows AND specific columns.
# [0, 4] → select 1st and 5th rows
# [1, 2] → select 2nd and 3rd columns

print(df.iloc[[0,4],[1,2]])

    Name Department
0   Arun        CSE
4  Rahul         IT

In [ ]:
# means select rows from position 0 up to 3 (excluding 3).
df.iloc[0:3]

   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80

In [ ]:
# get Label-based
df.loc[0,["Name"]]

Name    Arun
Name: 0, dtype: str

In [ ]:
# It filters the DataFrame and returns students from either CSE or IT.
result=df[
    (df["Department"]=="CSE") |
    (df["Department"]=="IT")
    ]
print(result)

   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80
4         105    Rahul         IT          88      88   91     86

In [86]:
# 1. find students with attendance >= 75
# 2. find students whose attendance is atleast 75 and python mark is atleast 80
# 3. calculate the average of python, sql and excel

# 1. attendance >= 75
cond=df[df["Attendance"]>=75].columns
cond

Index(['Student_ID', 'Name', 'Department', 'Attendance', 'Python', 'SQL',
       'Excel'],
      dtype='str')

In [ ]:
# 1. find Students with attendance >=75
df[(df['Attendance'] >= 75)]

   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80
4         105    Rahul         IT          88      88   91     86

In [87]:
#2. find students whose attendance is at least 75 AND Python mark is at least 80
df[(df['Attendance'] > 75) & (df['Python'] >= 80)][['Attendance','Python']]

   Attendance  Python
0          82      85
1          91      92
4          88      88

In [ ]:
# 3. Calculate the avg
(df["Python"]+df["SQL"]+df["Excel"])/3
(round(df["Python"]+df["SQL"]+df["Excel"])/3)

0    84.333333
1    91.666667
2    79.333333
3    69.000000
4    88.333333
dtype: float64

In [91]:
df["Average"]=((df["Python"]+df["SQL"]+df["Excel"])//3)
df

   Student_ID     Name Department  Attendance  Python  SQL  Excel  Average
0         101     Arun        CSE          82      85   78     90       84
1         102    Priya         IT          91      92   88     95       91
2         103  Karthik        CSE          76      76   82     80       79
3         104    Meena        ECE          68      65   70     72       69
4         105    Rahul         IT          88      88   91     86       88

In [100]:
# to store values in new column results 
# Comprehension - means write a single line code 
# so put the "pass"  in first and then condition


# df["Results"] → Creates a new column named "Results".
# Why? → To store the Pass/Fail result.

# = → Assigns the result to the "Results" column.
# Why? → To save the calculated values.

# df["Average"] → Selects the "Average" column.
# Why? → We need the average marks to check Pass/Fail.

# .apply() → Applies a function to each value in the column.
# Why? → To check each student's average individually.

# lambda avg: → Creates a small function.
# Why? → To perform the Pass/Fail check without defining a separate function.

# avg → Represents one student's average value at a time.

# "Pass" if avg >= 50 → Returns "Pass" when average is 50 or more.
# Why? → 50 is considered the passing mark.

# else "Fail" → Returns "Fail" when the average is below 50.
# Why? → The student has not reached the passing mark.


df["Results"]=df["Average"].apply( lambda avg:
   "Pass" if avg>=50 else "Faill"
)
df

,Student_ID,Name,Department,Attendance,Python,SQL,Excel,Average,Results
0,101,Arun,CSE,82,85,78,90,84,Pass
1,102,Priya,IT,91,92,88,95,91,Pass
2,103,Karthik,CSE,76,76,82,80,79,Pass
3,104,Meena,ECE,68,65,70,72,69,Pass
4,105,Rahul,IT,88,88,91,86,88,Pass

### Sorting

In [97]:
# Highest -  performing students (based on avg)
# here default  is ascending

df.sort_values(by="Average")

,Student_ID,Name,Department,Attendance,Python,SQL,Excel,Average,Results
3,104,Meena,ECE,68,65,70,72,69,Pass
2,103,Karthik,CSE,76,76,82,80,79,Pass
0,101,Arun,CSE,82,85,78,90,84,Pass
4,105,Rahul,IT,88,88,91,86,88,Pass
1,102,Priya,IT,91,92,88,95,91,Pass

In [ ]:
# for descending (based on attendance)
df.sort_values(by="Attendance",ascending=False)

,Student_ID,Name,Department,Attendance,Python,SQL,Excel,Average,Results
1,102,Priya,IT,91,92,88,95,91,Pass
4,105,Rahul,IT,88,88,91,86,88,Pass
0,101,Arun,CSE,82,85,78,90,84,Pass
2,103,Karthik,CSE,76,76,82,80,79,Pass
3,104,Meena,ECE,68,65,70,72,69,Pass

# GROUP BY

In [102]:
# What is the avg python mark for each dept
df.groupby("Department")["Python"].mean()

Department
CSE    80.5
ECE    65.0
IT     90.0
Name: Python, dtype: float64

In [114]:
# Number of students per dept
df.groupby("Department")["Student_ID"].count()

Department
CSE    2
ECE    1
IT     2
Name: Student_ID, dtype: int64

In [ ]:
# highest python mark by dept

Groupby with multiple metrics

In [116]:
df.groupby("Department").agg(
    {
        "Student_ID":"count",
        "Python":"mean",
        "Excel":"mean",
        "SQL":"mean",
        "Attendance":"mean"
    }
)

            Student_ID  Python  Excel   SQL  Attendance
Department
CSE                  2    80.5   85.0  80.0        79.0
ECE                  1    65.0   72.0  70.0        68.0
IT                   2    90.0   90.5  89.5        89.5

In [ ]:
# to find firsst mark in python in IT dept

# Read Files

In [11]:
%pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [22]:
exc=pd.read_excel(r"C:\Users\ELCOT\Desktop\JananiMurugan\Power BI\Time vs. Quality Datasheet.xlsx")

# to print only column names
exc.columns

# To print the entire excel sheet
print(exc)

       Name  Time per Task (seconds)  Quality (%)
0   Charlie                      1.5         91.4
1      Indu                      1.6         92.9
2   Prajwal                      1.7         92.5
3     Vimla                      0.9         87.0
4      Amit                      2.2         92.5
5     Binny                      0.7         85.0
6   Pradyut                      2.3         91.6
7   Diwakar                      0.6         96.0
8     Amrit                      1.2         92.9
9    Debdas                      1.2         92.5
10    Anika                      1.4         91.5
11  Haritha                      1.4         91.7
12   Dhanya                      1.6         92.3
13   Venkat                      1.7         91.7
14    Afzal                      2.2         92.1
15   Prachi                      2.2         92.1
16  Anushka                      2.2         85.0
17   Firoza                      2.3         92.1
18    Mange                      2.1         92.6
19    Vimal                      2.3         92.6
20     Dipa                      2.3         92.2
21    Anand                      2.4         93.8
22    Gopal                      1.9         91.9
23    Vijay                      1.9         92.3
24  Preetha                      2.2         92.0
25    Nupur                      2.2         91.8
26     Neha                      3.2         92.2
27    Deepa                      2.7         92.0
28   Aniket                      3.2         91.9
29   Dhruti                      2.7         92.4
30    Wasim                      3.4         91.8
31    Arohi                      2.9         92.7
32    Vinay                      2.8         92.4
33  Praveen                      3.6         85.0
34     Biju                      3.5         84.0