<h1><center> DECISION TREE CLASSIFIER </h1></center>

In [177]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [178]:
df=pd.read_excel(r"C:\Users\ELCOT\Desktop\JananiMurugan\Machine_Learning\Self_Task_ML_Models\DT_classifier\Dataset\credit_data.xlsx")
df

    Age   Income Education Married Default
0    25  50000.0  Bachelor     Yes      No
1    32  62000.0    Master      No      No
2    40      NaN       PhD     Yes     Yes
3    28  45000.0  Bachelor     NaN      No
4    35  70000.0       NaN     Yes      No
5    42  80000.0    Master     Yes     Yes
6    30  52000.0  Bachelor      No      No
7    38  65000.0       PhD     Yes     Yes
8    29      NaN  Bachelor      No      No
9    45  90000.0    Master     Yes     Yes
10   33  58000.0  Bachelor      No      No
11   41  75000.0       PhD     Yes     Yes
12   27  48000.0       NaN      No      No
13   36  72000.0    Master     Yes      No
14   39  68000.0  Bachelor     Yes     Yes
15   31      NaN       PhD      No      No
16   44  85000.0    Master     Yes     Yes
17   26  47000.0  Bachelor      No      No
18   37  71000.0       PhD     Yes     Yes
19   34  60000.0       NaN      No      No
20   43  82000.0    Master     Yes     Yes
21   28  49000.0  Bachelor      No      No
22   40  77000.0       PhD     Yes     Yes
23   32  56000.0       NaN      No      No
24   46  93000.0    Master     Yes     Yes
25   29  51000.0  Bachelor      No      No
26   38  69000.0       PhD     Yes     Yes
27   30      NaN  Bachelor      No      No
28   42  81000.0    Master     Yes     Yes
29   35  64000.0       NaN     Yes      No

In [179]:
df.isnull().sum()

Age          0
Income       4
Education    5
Married      1
Default      0
dtype: int64

In [180]:
df["Education"].mode()[0]

'Bachelor'

In [181]:
df["Education"] = df["Education"].fillna(df["Education"].mode()[0])
df["Education"]

0     Bachelor
1       Master
2          PhD
3     Bachelor
4     Bachelor
5       Master
6     Bachelor
7          PhD
8     Bachelor
9       Master
10    Bachelor
11         PhD
12    Bachelor
13      Master
14    Bachelor
15         PhD
16      Master
17    Bachelor
18         PhD
19    Bachelor
20      Master
21    Bachelor
22         PhD
23    Bachelor
24      Master
25    Bachelor
26         PhD
27    Bachelor
28      Master
29    Bachelor
Name: Education, dtype: str

In [182]:
df["Income"] = df["Income"].fillna(df["Income"].mean())
df["Income"] = df["Income"].round(2)

In [183]:
df["Married"] = df["Married"].fillna(df["Married"].mode()[0])
df["Married"]

0     Yes
1      No
2     Yes
3     Yes
4     Yes
5     Yes
6      No
7     Yes
8      No
9     Yes
10     No
11    Yes
12     No
13    Yes
14    Yes
15     No
16    Yes
17     No
18    Yes
19     No
20    Yes
21     No
22    Yes
23     No
24    Yes
25     No
26    Yes
27     No
28    Yes
29    Yes
Name: Married, dtype: str

In [184]:
print(df)

    Age    Income Education Married Default
0    25  50000.00  Bachelor     Yes      No
1    32  62000.00    Master      No      No
2    40  66153.85       PhD     Yes     Yes
3    28  45000.00  Bachelor     Yes      No
4    35  70000.00  Bachelor     Yes      No
5    42  80000.00    Master     Yes     Yes
6    30  52000.00  Bachelor      No      No
7    38  65000.00       PhD     Yes     Yes
8    29  66153.85  Bachelor      No      No
9    45  90000.00    Master     Yes     Yes
10   33  58000.00  Bachelor      No      No
11   41  75000.00       PhD     Yes     Yes
12   27  48000.00  Bachelor      No      No
13   36  72000.00    Master     Yes      No
14   39  68000.00  Bachelor     Yes     Yes
15   31  66153.85       PhD      No      No
16   44  85000.00    Master     Yes     Yes
17   26  47000.00  Bachelor      No      No
18   37  71000.00       PhD     Yes     Yes
19   34  60000.00  Bachelor      No      No
20   43  82000.00    Master     Yes     Yes
21   28  49000.00  Bachelor      No      No
22   40  77000.00       PhD     Yes     Yes
23   32  56000.00  Bachelor      No      No
24   46  93000.00    Master     Yes     Yes
25   29  51000.00  Bachelor      No      No
26   38  69000.00       PhD     Yes     Yes
27   30  66153.85  Bachelor      No      No
28   42  81000.00    Master     Yes     Yes
29   35  64000.00  Bachelor     Yes      No

In [185]:
df.isnull().sum()

Age          0
Income       0
Education    0
Married      0
Default      0
dtype: int64

##### Feature and target

In [186]:
# Feature selection
X = df[[
    "Age",
    "Income",
    "Education",
    "Married"
]]

# Target 
y = df["Default"]

In [187]:
pd.concat([X,y],axis=1)

    Age    Income Education Married Default
0    25  50000.00  Bachelor     Yes      No
1    32  62000.00    Master      No      No
2    40  66153.85       PhD     Yes     Yes
3    28  45000.00  Bachelor     Yes      No
4    35  70000.00  Bachelor     Yes      No
5    42  80000.00    Master     Yes     Yes
6    30  52000.00  Bachelor      No      No
7    38  65000.00       PhD     Yes     Yes
8    29  66153.85  Bachelor      No      No
9    45  90000.00    Master     Yes     Yes
10   33  58000.00  Bachelor      No      No
11   41  75000.00       PhD     Yes     Yes
12   27  48000.00  Bachelor      No      No
13   36  72000.00    Master     Yes      No
14   39  68000.00  Bachelor     Yes     Yes
15   31  66153.85       PhD      No      No
16   44  85000.00    Master     Yes     Yes
17   26  47000.00  Bachelor      No      No
18   37  71000.00       PhD     Yes     Yes
19   34  60000.00  Bachelor      No      No
20   43  82000.00    Master     Yes     Yes
21   28  49000.00  Bachelor      No      No
22   40  77000.00       PhD     Yes     Yes
23   32  56000.00  Bachelor      No      No
24   46  93000.00    Master     Yes     Yes
25   29  51000.00  Bachelor      No      No
26   38  69000.00       PhD     Yes     Yes
27   30  66153.85  Bachelor      No      No
28   42  81000.00    Master     Yes     Yes
29   35  64000.00  Bachelor     Yes      No

##### Encoding the categorical column

##### Label encoding

##### (i). for married

In [188]:
encod = LabelEncoder()

X["Encoded_Married"] = encod.fit_transform(X["Married"])
X["Encoded_Married"]

0     1
1     0
2     1
3     1
4     1
5     1
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    1
15    0
16    1
17    0
18    1
19    0
20    1
21    0
22    1
23    0
24    1
25    0
26    1
27    0
28    1
29    1
Name: Encoded_Married, dtype: int64

#####  (ii). for default

In [189]:
df["Encoded_Default"] = encod.fit_transform(df["Default"])
df["Encoded_Default"]

0     0
1     0
2     1
3     0
4     0
5     1
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    0
14    1
15    0
16    1
17    0
18    1
19    0
20    1
21    0
22    1
23    0
24    1
25    0
26    1
27    0
28    1
29    0
Name: Encoded_Default, dtype: int64

##### On-Hot encoding

##### (iii).  for  Education

In [190]:
df = pd.get_dummies(df, columns=["Education"], dtype=int)

In [191]:
print(df.to_string())

    Age    Income Married Default  Encoded_Default  Education_Bachelor  Education_Master  Education_PhD
0    25  50000.00     Yes      No                0                   1                 0              0
1    32  62000.00      No      No                0                   0                 1              0
2    40  66153.85     Yes     Yes                1                   0                 0              1
3    28  45000.00     Yes      No                0                   1                 0              0
4    35  70000.00     Yes      No                0                   1                 0              0
5    42  80000.00     Yes     Yes                1                   0                 1              0
6    30  52000.00      No      No                0                   1                 0              0
7    38  65000.00     Yes     Yes                1                   0                 0              1
8    29  66153.85      No      No                0                   1                 0              0
9    45  90000.00     Yes     Yes                1                   0                 1              0
10   33  58000.00      No      No                0                   1                 0              0
11   41  75000.00     Yes     Yes                1                   0                 0              1
12   27  48000.00      No      No                0                   1                 0              0
13   36  72000.00     Yes      No                0                   0                 1              0
14   39  68000.00     Yes     Yes                1                   1                 0              0
15   31  66153.85      No      No                0                   0                 0              1
16   44  85000.00     Yes     Yes                1                   0                 1              0
17   26  47000.00      No      No                0                   1                 0              0
18   37  71000.00     Yes     Yes                1                   0                 0              1
19   34  60000.00      No      No                0                   1                 0              0
20   43  82000.00     Yes     Yes                1                   0                 1              0
21   28  49000.00      No      No                0                   1                 0              0
22   40  77000.00     Yes     Yes                1                   0                 0              1
23   32  56000.00      No      No                0                   1                 0              0
24   46  93000.00     Yes     Yes                1                   0                 1              0
25   29  51000.00      No      No                0                   1                 0              0
26   38  69000.00     Yes     Yes                1                   0                 0              1
27   30  66153.85      No      No                0                   1                 0              0
28   42  81000.00     Yes     Yes                1                   0                 1              0
29   35  64000.00     Yes      No                0                   1                 0              0